/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EnterHostRouteImport } from './routes/enter-host'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as HostRouteRouteImport } from './routes/_host/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSignUpRouteImport } from './routes/dashboard/sign-up'
import { Route as DashboardSignInRouteImport } from './routes/dashboard/sign-in'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as HostSetupRouteImport } from './routes/_host/setup'
import { Route as DashboardAuthedRouteRouteImport } from './routes/dashboard/_authed/route'
import { Route as HostAdminRouteRouteImport } from './routes/_host/admin/route'
import { Route as DashboardAuthedIndexRouteImport } from './routes/dashboard/_authed/index'
import { Route as HostAdminIndexRouteImport } from './routes/_host/admin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as HostAdminTagsRouteImport } from './routes/_host/admin/tags'
import { Route as HostAdminMembersRouteImport } from './routes/_host/admin/members'

const EnterHostRoute = EnterHostRouteImport.update({
  id: '/enter-host',
  path: '/enter-host',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRouteRoute = HostRouteRouteImport.update({
  id: '/_host',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSignUpRoute = DashboardSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSignInRoute = DashboardSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSetupRoute = HostSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => HostRouteRoute,
} as any)
const DashboardAuthedRouteRoute = DashboardAuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const HostAdminRouteRoute = HostAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => HostRouteRoute,
} as any)
const DashboardAuthedIndexRoute = DashboardAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAuthedRouteRoute,
} as any)
const HostAdminIndexRoute = HostAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostAdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HostAdminTagsRoute = HostAdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => HostAdminRouteRoute,
} as any)
const HostAdminMembersRoute = HostAdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => HostAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardAuthedRouteRouteWithChildren
  '/enter-host': typeof EnterHostRoute
  '/admin': typeof HostAdminRouteRouteWithChildren
  '/setup': typeof HostSetupRoute
  '/api/ping': typeof ApiPingRoute
  '/dashboard/sign-in': typeof DashboardSignInRoute
  '/dashboard/sign-up': typeof DashboardSignUpRoute
  '/admin/members': typeof HostAdminMembersRoute
  '/admin/tags': typeof HostAdminTagsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof HostAdminIndexRoute
  '/dashboard/': typeof DashboardAuthedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardAuthedIndexRoute
  '/enter-host': typeof EnterHostRoute
  '/setup': typeof HostSetupRoute
  '/api/ping': typeof ApiPingRoute
  '/dashboard/sign-in': typeof DashboardSignInRoute
  '/dashboard/sign-up': typeof DashboardSignUpRoute
  '/admin/members': typeof HostAdminMembersRoute
  '/admin/tags': typeof HostAdminTagsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof HostAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_host': typeof HostRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/enter-host': typeof EnterHostRoute
  '/_host/admin': typeof HostAdminRouteRouteWithChildren
  '/dashboard/_authed': typeof DashboardAuthedRouteRouteWithChildren
  '/_host/setup': typeof HostSetupRoute
  '/api/ping': typeof ApiPingRoute
  '/dashboard/sign-in': typeof DashboardSignInRoute
  '/dashboard/sign-up': typeof DashboardSignUpRoute
  '/_host/admin/members': typeof HostAdminMembersRoute
  '/_host/admin/tags': typeof HostAdminTagsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_host/admin/': typeof HostAdminIndexRoute
  '/dashboard/_authed/': typeof DashboardAuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/enter-host'
    | '/admin'
    | '/setup'
    | '/api/ping'
    | '/dashboard/sign-in'
    | '/dashboard/sign-up'
    | '/admin/members'
    | '/admin/tags'
    | '/api/auth/$'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/enter-host'
    | '/setup'
    | '/api/ping'
    | '/dashboard/sign-in'
    | '/dashboard/sign-up'
    | '/admin/members'
    | '/admin/tags'
    | '/api/auth/$'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_host'
    | '/dashboard'
    | '/enter-host'
    | '/_host/admin'
    | '/dashboard/_authed'
    | '/_host/setup'
    | '/api/ping'
    | '/dashboard/sign-in'
    | '/dashboard/sign-up'
    | '/_host/admin/members'
    | '/_host/admin/tags'
    | '/api/auth/$'
    | '/_host/admin/'
    | '/dashboard/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HostRouteRoute: typeof HostRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  EnterHostRoute: typeof EnterHostRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/enter-host': {
      id: '/enter-host'
      path: '/enter-host'
      fullPath: '/enter-host'
      preLoaderRoute: typeof EnterHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_host': {
      id: '/_host'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HostRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sign-up': {
      id: '/dashboard/sign-up'
      path: '/sign-up'
      fullPath: '/dashboard/sign-up'
      preLoaderRoute: typeof DashboardSignUpRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/sign-in': {
      id: '/dashboard/sign-in'
      path: '/sign-in'
      fullPath: '/dashboard/sign-in'
      preLoaderRoute: typeof DashboardSignInRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_host/setup': {
      id: '/_host/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof HostSetupRouteImport
      parentRoute: typeof HostRouteRoute
    }
    '/dashboard/_authed': {
      id: '/dashboard/_authed'
      path: ''
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardAuthedRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_host/admin': {
      id: '/_host/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof HostAdminRouteRouteImport
      parentRoute: typeof HostRouteRoute
    }
    '/dashboard/_authed/': {
      id: '/dashboard/_authed/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardAuthedIndexRouteImport
      parentRoute: typeof DashboardAuthedRouteRoute
    }
    '/_host/admin/': {
      id: '/_host/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof HostAdminIndexRouteImport
      parentRoute: typeof HostAdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_host/admin/tags': {
      id: '/_host/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof HostAdminTagsRouteImport
      parentRoute: typeof HostAdminRouteRoute
    }
    '/_host/admin/members': {
      id: '/_host/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof HostAdminMembersRouteImport
      parentRoute: typeof HostAdminRouteRoute
    }
  }
}

interface HostAdminRouteRouteChildren {
  HostAdminMembersRoute: typeof HostAdminMembersRoute
  HostAdminTagsRoute: typeof HostAdminTagsRoute
  HostAdminIndexRoute: typeof HostAdminIndexRoute
}

const HostAdminRouteRouteChildren: HostAdminRouteRouteChildren = {
  HostAdminMembersRoute: HostAdminMembersRoute,
  HostAdminTagsRoute: HostAdminTagsRoute,
  HostAdminIndexRoute: HostAdminIndexRoute,
}

const HostAdminRouteRouteWithChildren = HostAdminRouteRoute._addFileChildren(
  HostAdminRouteRouteChildren,
)

interface HostRouteRouteChildren {
  HostAdminRouteRoute: typeof HostAdminRouteRouteWithChildren
  HostSetupRoute: typeof HostSetupRoute
}

const HostRouteRouteChildren: HostRouteRouteChildren = {
  HostAdminRouteRoute: HostAdminRouteRouteWithChildren,
  HostSetupRoute: HostSetupRoute,
}

const HostRouteRouteWithChildren = HostRouteRoute._addFileChildren(
  HostRouteRouteChildren,
)

interface DashboardAuthedRouteRouteChildren {
  DashboardAuthedIndexRoute: typeof DashboardAuthedIndexRoute
}

const DashboardAuthedRouteRouteChildren: DashboardAuthedRouteRouteChildren = {
  DashboardAuthedIndexRoute: DashboardAuthedIndexRoute,
}

const DashboardAuthedRouteRouteWithChildren =
  DashboardAuthedRouteRoute._addFileChildren(DashboardAuthedRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAuthedRouteRoute: typeof DashboardAuthedRouteRouteWithChildren
  DashboardSignInRoute: typeof DashboardSignInRoute
  DashboardSignUpRoute: typeof DashboardSignUpRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAuthedRouteRoute: DashboardAuthedRouteRouteWithChildren,
  DashboardSignInRoute: DashboardSignInRoute,
  DashboardSignUpRoute: DashboardSignUpRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HostRouteRoute: HostRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  EnterHostRoute: EnterHostRoute,
  ApiPingRoute: ApiPingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
