/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as EnterHostRouteImport } from './routes/enter-host'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardWorkspaceIdIndexRouteImport } from './routes/dashboard/$workspaceId/index'
import { Route as DashboardauthSignUpRouteImport } from './routes/dashboard/(auth)/sign-up'
import { Route as DashboardauthSignInRouteImport } from './routes/dashboard/(auth)/sign-in'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterHostRoute = EnterHostRouteImport.update({
  id: '/enter-host',
  path: '/enter-host',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWorkspaceIdIndexRoute =
  DashboardWorkspaceIdIndexRouteImport.update({
    id: '/$workspaceId/',
    path: '/$workspaceId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardauthSignUpRoute = DashboardauthSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardauthSignInRoute = DashboardauthSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/enter-host': typeof EnterHostRoute
  '/setup': typeof SetupRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/sign-in': typeof DashboardauthSignInRoute
  '/dashboard/sign-up': typeof DashboardauthSignUpRoute
  '/dashboard/$workspaceId': typeof DashboardWorkspaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enter-host': typeof EnterHostRoute
  '/setup': typeof SetupRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/sign-in': typeof DashboardauthSignInRoute
  '/dashboard/sign-up': typeof DashboardauthSignUpRoute
  '/dashboard/$workspaceId': typeof DashboardWorkspaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/enter-host': typeof EnterHostRoute
  '/setup': typeof SetupRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/(auth)/sign-in': typeof DashboardauthSignInRoute
  '/dashboard/(auth)/sign-up': typeof DashboardauthSignUpRoute
  '/dashboard/$workspaceId/': typeof DashboardWorkspaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/enter-host'
    | '/setup'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/sign-in'
    | '/dashboard/sign-up'
    | '/dashboard/$workspaceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/enter-host'
    | '/setup'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/sign-in'
    | '/dashboard/sign-up'
    | '/dashboard/$workspaceId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/enter-host'
    | '/setup'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/(auth)/sign-in'
    | '/dashboard/(auth)/sign-up'
    | '/dashboard/$workspaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  EnterHostRoute: typeof EnterHostRoute
  SetupRoute: typeof SetupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enter-host': {
      id: '/enter-host'
      path: '/enter-host'
      fullPath: '/enter-host'
      preLoaderRoute: typeof EnterHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/$workspaceId/': {
      id: '/dashboard/$workspaceId/'
      path: '/$workspaceId'
      fullPath: '/dashboard/$workspaceId'
      preLoaderRoute: typeof DashboardWorkspaceIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/(auth)/sign-up': {
      id: '/dashboard/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/dashboard/sign-up'
      preLoaderRoute: typeof DashboardauthSignUpRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/(auth)/sign-in': {
      id: '/dashboard/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/dashboard/sign-in'
      preLoaderRoute: typeof DashboardauthSignInRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardauthSignInRoute: typeof DashboardauthSignInRoute
  DashboardauthSignUpRoute: typeof DashboardauthSignUpRoute
  DashboardWorkspaceIdIndexRoute: typeof DashboardWorkspaceIdIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardauthSignInRoute: DashboardauthSignInRoute,
  DashboardauthSignUpRoute: DashboardauthSignUpRoute,
  DashboardWorkspaceIdIndexRoute: DashboardWorkspaceIdIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  EnterHostRoute: EnterHostRoute,
  SetupRoute: SetupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
